version: '3.7'
services:

  web:
    container_name: 'api_and_celery'
    build: .
    command: sh -c "/app/.docker_compose_scripts/web_services_init.sh && tail -f /dev/null"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - HOST_DATABASE=database
      - RABBITMQ_SERVER=rabbitmq
    ports:
      - '8000:8000'
    depends_on:
      db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  db:
    image: postgres:12-alpine
    container_name: 'database'
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # Creates a defaulte database named 'web_analyzer'
      - POSTGRES_DB=web_analyzer
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres", "-d", "web_analyzer"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 1
    #volumes:
    #    - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #    - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    #networks:
    #     - rabbitmq_go_net