version: '3.7'
services:

  web:
    build: .
    command: sh -c "/app/web_services_init.sh"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '8000:8000'
    depends_on:
      - db
    volumes:
      - .docker_compose_scripts/web_services_init.sh:/app/web_services_init.sh

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - /var/lib/postgresql/data
      - .docker_compose_scripts/init.sql:/docker-entrypoint-initdb.d/init.sql