# Generated by Django 5.0.1 on 2024-05-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataExtracted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_from', models.CharField(default='', max_length=30)),
                ('domain', models.CharField(default='')),
                ('data_extracted', models.JSONField(default=dict)),
                ('white_list', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='LastLineRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_line_read_alien_vault', models.IntegerField(default=0)),
                ('last_line_read_virus_total', models.IntegerField(default=0)),
                ('last_line_read_pulsedive', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pulsedive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_day_used', models.DateField()),
                ('total_querys_on_month', models.IntegerField(default=0)),
            ],
        ),
    ]
