# Generated by Django 5.0.1 on 2024-04-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberintelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastlineread',
            name='last_line_read_pulsedive',
            field=models.IntegerField(default=0),
        ),
    ]
